U1/GestioneHotelApp/Controllers/CercaController.cs
using GestioneHotelApp.Data;
using GestioneHotelApp.Models;
using GestioneHotelApp.DAO;
using Microsoft.AspNetCore.Mvc;

namespace GestioneHotelApp.Controllers
{
    public class CercaController : Controller
    {
        private readonly PrenotazioneDao _prenotazioneDao;

        public CercaController(PrenotazioneDao prenotazioneDao)
        {
            _prenotazioneDao = prenotazioneDao;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult RicercaPrenotazioni(string nome, string cognome)
        {
            var prenotazioni = _prenotazioneDao.GetPrenotazioniByNomeCognome(nome, cognome);
            return PartialView("PrenotazioniResult", prenotazioni);
        }
    }
}

U1/GestioneHotelApp/Controllers/PrenotazioniController.cs
using Microsoft.AspNetCore.Mvc;
using GestioneHotelApp.Models;
using GestioneHotelApp.DAO;
using System.Collections.Generic;

namespace GestioneHotelApp.Controllers
{
    public class PrenotazioniController : Controller
    {
        private readonly PrenotazioneDao _prenotazioneDao;

        public PrenotazioniController(PrenotazioneDao prenotazioneDao)
        {
            _prenotazioneDao = prenotazioneDao;
        }

        public IActionResult Index()
        {
            var prenotazioni = _prenotazioneDao.GetAllPrenotazioni();
            return View(prenotazioni);
        }
    }
}

U1/GestioneHotelApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GestioneHotelApp</title>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GestioneHotelApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Prenotazioni" asp-action="Index">Prenotazioni</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cerca" asp-action="Index">Cerca Prenotazioni</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - GestioneHotelApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>